// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgbQZHQ-OSq1lar2QZV9syb84zf213PF4',
    appId: '1:76249013032:web:52095359e712b54c33ce1d',
    messagingSenderId: '76249013032',
    projectId: 'mega-petertan343',
    authDomain: 'mega-petertan343.firebaseapp.com',
    storageBucket: 'mega-petertan343.appspot.com',
    measurementId: 'G-95VMLCSY1S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBP0KypRaQPAuwKM8fnaMiJLLmEhqGc_UU',
    appId: '1:76249013032:android:0b7d3839eab0f06c33ce1d',
    messagingSenderId: '76249013032',
    projectId: 'mega-petertan343',
    storageBucket: 'mega-petertan343.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbyIiXDxBbjGJiB3L0sQipcA5YDDEHMtw',
    appId: '1:76249013032:ios:bf9d9ab041e043ad33ce1d',
    messagingSenderId: '76249013032',
    projectId: 'mega-petertan343',
    storageBucket: 'mega-petertan343.appspot.com',
    iosClientId: '76249013032-hotcph38ko678gjhcaspal9q8i4vpho1.apps.googleusercontent.com',
    iosBundleId: 'com.example.megaPetertan343',
  );
}
