// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5a-JMQ4oOqrxlYqXheUU0WYJCKPz7-oc',
    appId: '1:181211131869:android:30182273652321e4b65034',
    messagingSenderId: '181211131869',
    projectId: 'mega-app-1ea75',
    storageBucket: 'mega-app-1ea75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK2NT44I7ZH2PbgMWdomOJLQXLwBg_Upw',
    appId: '1:181211131869:ios:8032b2a68c39b349b65034',
    messagingSenderId: '181211131869',
    projectId: 'mega-app-1ea75',
    storageBucket: 'mega-app-1ea75.appspot.com',
    androidClientId: '181211131869-9r4gkerthc6gqfnl8fvthj10br6t9s30.apps.googleusercontent.com',
    iosClientId: '181211131869-vuj4jv4tgnek1v40uie6mq37g9070lfq.apps.googleusercontent.com',
    iosBundleId: 'com.example.megaPetertan343',
  );
}
